# Generated by Django 4.1.5 on 2023-01-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
